[
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_admin",
				"type": "address"
			}
		],
		"name": "adicionarAdmin",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_org",
				"type": "address"
			}
		],
		"name": "adicionarOrganizador",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"stateMutability": "nonpayable",
		"type": "constructor"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "address",
				"name": "admin",
				"type": "address"
			}
		],
		"name": "AdminAdicionado",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "address",
				"name": "organizador",
				"type": "address"
			}
		],
		"name": "OrganizadorAdicionado",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "bytes32",
				"name": "id",
				"type": "bytes32"
			},
			{
				"indexed": false,
				"internalType": "string",
				"name": "nome_aluno",
				"type": "string"
			},
			{
				"indexed": false,
				"internalType": "string",
				"name": "matricula",
				"type": "string"
			},
			{
				"indexed": false,
				"internalType": "bytes32",
				"name": "evento_id",
				"type": "bytes32"
			}
		],
		"name": "certificadoRegistrado",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "bytes32",
				"name": "id",
				"type": "bytes32"
			},
			{
				"indexed": false,
				"internalType": "string",
				"name": "nome",
				"type": "string"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "data",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "cargaHoraria",
				"type": "uint256"
			}
		],
		"name": "eventoRegistrado",
		"type": "event"
	},
	{
		"inputs": [
			{
				"internalType": "string",
				"name": "_nome_aluno",
				"type": "string"
			},
			{
				"internalType": "string",
				"name": "_matricula",
				"type": "string"
			},
			{
				"internalType": "bytes32",
				"name": "_evento_id",
				"type": "bytes32"
			}
		],
		"name": "registrarCertificado",
		"outputs": [
			{
				"internalType": "bytes32",
				"name": "",
				"type": "bytes32"
			}
		],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "string",
				"name": "_nome",
				"type": "string"
			},
			{
				"internalType": "uint256",
				"name": "_data",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "_cargaHoraria",
				"type": "uint256"
			}
		],
		"name": "registrarEvento",
		"outputs": [
			{
				"internalType": "bytes32",
				"name": "",
				"type": "bytes32"
			}
		],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_admin",
				"type": "address"
			}
		],
		"name": "removerAdmin",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_org",
				"type": "address"
			}
		],
		"name": "removerOrganizador",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"name": "admins",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "",
				"type": "bytes32"
			}
		],
		"name": "certificados",
		"outputs": [
			{
				"internalType": "string",
				"name": "nome_aluno",
				"type": "string"
			},
			{
				"internalType": "string",
				"name": "matricula",
				"type": "string"
			},
			{
				"internalType": "bytes32",
				"name": "evento_id",
				"type": "bytes32"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "id",
				"type": "bytes32"
			}
		],
		"name": "containsCertificado",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "id",
				"type": "bytes32"
			}
		],
		"name": "containsEvento",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "",
				"type": "bytes32"
			}
		],
		"name": "eventos",
		"outputs": [
			{
				"internalType": "string",
				"name": "nome",
				"type": "string"
			},
			{
				"internalType": "uint256",
				"name": "data",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "cargaHoraria",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "id",
				"type": "bytes32"
			}
		],
		"name": "obterCertificado",
		"outputs": [
			{
				"components": [
					{
						"internalType": "string",
						"name": "nome_aluno",
						"type": "string"
					},
					{
						"internalType": "string",
						"name": "matricula",
						"type": "string"
					},
					{
						"internalType": "bytes32",
						"name": "evento_id",
						"type": "bytes32"
					}
				],
				"internalType": "struct Entidades.Certificado",
				"name": "certificado",
				"type": "tuple"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "id",
				"type": "bytes32"
			}
		],
		"name": "obterEvento",
		"outputs": [
			{
				"components": [
					{
						"internalType": "string",
						"name": "nome",
						"type": "string"
					},
					{
						"internalType": "uint256",
						"name": "data",
						"type": "uint256"
					},
					{
						"internalType": "uint256",
						"name": "cargaHoraria",
						"type": "uint256"
					}
				],
				"internalType": "struct Entidades.Evento",
				"name": "evento",
				"type": "tuple"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"name": "organizadores",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "owner",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	}
]